# Generated by Django 6.0.5 on 2026-05-22 06:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_todo',
            name='date',
            field=models.DateField(default=datetime.date(2026, 5, 22)),
            preserve_default=False,
        ),
    ]
